spring.application.name=Fitness_Tracker-Monolith-Architecture
#Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

